package model.repositories;


import java.util.ArrayList;
import java.util.List;
import model.entities.*;


public class Bill {
    private final List<BillPosition> list = new ArrayList<>();
        
    public void addDataToBill(Entity entity){        
        if(entity instanceof Position){
            list.add(new BillPosition());
            list.get(list.size() - 1).setPosition((Position)entity);
        }
        if(entity instanceof Volume){
            BillPosition position = list.get(list.size() - 1);
            position.setVolume((Volume)entity);                        
            position.setCost(Menu.getInstance().getCost(position.getPosition().getId(),
                    position.getVolume().getId()));
        }
    }
    
    public List<BillPosition> getList(){
        return list;
    }           
    
    //TODO: 1. save idMenu to PositionBill table
    //      2. fill in Bill table with idBill (AutoGenerated), 
    //         idUser (default for the present), totalCost, id_Z and DateTime 
    public void saveBill(){
       
    }
    
    
    
    @Override
    public String toString(){
        StringBuilder resultString = new StringBuilder();      
        for(int i = 0; i < list.size(); i++){
            resultString.append("/")
                    .append(i + 1)
                    .append(" ")
                    .append(list.get(i))
                    .append("\n");
        }
        return resultString.toString();
    }
}
