package model.repositories;


import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.entities.*;
import utils.DB.DBUtils;


public class Bill {
    
    private float totalCost = 0;
    private final List<BillPosition> list = new ArrayList<>();
        
    public void addDataToBill(Entity entity){        
        if(entity instanceof Position){
            list.add(new BillPosition   ());
            list.get(list.size() - 1).setPosition((Position)entity);
        }
        if(entity instanceof Volume){
            BillPosition position = list.get(list.size() - 1);
            position.setVolume((Volume)entity);   
            MenuItem menuItem = Menu.getInstance().getItemByIds(position.getPosition().getId(),
                    position.getVolume().getId());
            position.setCost(menuItem.getCost());
            position.setIdMenu(menuItem.getId());
            updateTotalCost();
        }        
    }
    
    public void updateTotalCost(){
        totalCost = list.stream().map(posititon -> posititon.getCost()).reduce((m, n) -> m + n).get();
    }
    
    public List<BillPosition> getList(){
        return list;
    }           
    
    //TODO: 1. save idMenu to PositionBill table
    //      2. fill in Bill table with idBill (AutoGenerated), 
    //         idUser (default for the present), totalCost, id_Z and DateTime 
    public void saveBill(){
        
        try {
            PreparedStatement insertStatement = DBUtils.getInstance()
                    .getConnection()
                    .prepareStatement("INSERT INTO positionBill (idBill, idMenu) VALUES (?, ?)");
            for(BillPosition position : list){
                insertStatement.setString(1, "1");
                insertStatement.setString(2, position.getIdMenu());
                insertStatement.execute();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Bill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    @Override
    public String toString(){
        StringBuilder resultString = new StringBuilder();      
        for(int i = 0; i < list.size(); i++){
            resultString.append("/")
                    .append(i + 1)
                    .append(" ")
                    .append(list.get(i))
                    .append("\n");                
        }
        resultString.append("\nTotal: ")
                    .append(totalCost/100);
        return resultString.toString();
    }
}
